apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: nfs-subdir-external-provisioner
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-09-21T16:14:55Z"
  generation: 1
  labels:
    app: nfs-subdir-external-provisioner
    app.kubernetes.io/managed-by: Helm
    chart: nfs-subdir-external-provisioner-4.0.18
    heritage: Helm
    release: nfs-subdir-external-provisioner
  name: nfs-subdir-external-provisioner
  namespace: default
  resourceVersion: "776"
  uid: 1dda1559-a2df-47b7-b98b-9b6f6a812cbe
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
      release: nfs-subdir-external-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs-subdir-external-provisioner
        release: nfs-subdir-external-provisioner
    spec:
      containers:
      - env:
        - name: PROVISIONER_NAME
          value: cluster.local/nfs-subdir-external-provisioner
        - name: NFS_SERVER
          value: 172.16.0.22
        - name: NFS_PATH
          value: /mnt/tank/edu
        image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
        imagePullPolicy: IfNotPresent
        name: nfs-subdir-external-provisioner
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /persistentvolumes
          name: nfs-subdir-external-provisioner-root
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nfs-subdir-external-provisioner
      serviceAccountName: nfs-subdir-external-provisioner
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-subdir-external-provisioner-root
        nfs:
          path: /mnt/tank/edu
          server: 172.16.0.22
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-09-21T16:14:56Z"
    lastUpdateTime: "2024-09-21T16:14:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-09-21T16:14:55Z"
    lastUpdateTime: "2024-09-21T16:14:56Z"
    message: ReplicaSet "nfs-subdir-external-provisioner-65b775f865" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1